name: CI

on:
  pull_request:
    branches: [ master ]

jobs:
  test-docker:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: create docker dev image
      run: make build-dev

    - name: run docker tests
      run: make run-tests

    - name: cleanup
      run: make run-cleanup